### ISSUE TITLE
Better link to the bin

### ISSUE THREAD

**Issue by Astremy** [readthedocs-fr/bin-client-discord#26]
Je pense que l'idée de convertir les gros blocs de codes en bin accessibles facilement est vraiment une bonne idée.

Je me dit toutefois qu'elle pourrait être encore améliorée. Un petit problème c'est que le bot "s'incruste" dans les conversations pour donner le lien.

On pourrais peut-être faire en sorte que le lien généré soit donné de manière un peu plus propre.

Pour cela, je pense que cela pourrait être très bien de le faire à l'aide de webhook.

Les webhooks sont des éléments attachés à un channel qui permettent d'envoyer des messages comme si c'était un réel bot. La particularité intéressante est que l'on peux personnaliser le nom et la photo de profil pour mettre ce que l'on veux.

Je pense que cela pourrait être bien d'utiliser ça, pour faire comme si c'était la personne qui a envoyée le code qui envoie le lien, en plus cela n'est pas forcément problématique parce que on peut utiliser des embeds avec le webhook.

De plus quelque-chose de sympa en plus à faire, ça pourrait être de mettre une image du code un peu comme [Carbon](https://carbon.now.sh/) pour les codes assez courts pour rendre bien.

**Comment by Aakodal** [comment]
L'idée des webhooks a été l'idée originale mais a été abandonnée ; un webhook est propre à un channel, on pourrait donc monter à théoriquement 3000 webhooks (un par user) par channels.

**Comment by Aakodal** [comment]
De plus comme l'a souligné AntoineJT sur Discord, il a refusé l'idée, et c'est lui qui se charge du cahier des charges.
